version: 2.1
workflows:
    version: 2.1
    build_and_test:
      jobs:
        - build
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command